### ISSUE TITLE
Issue with provided jar in release 2.0.0.1: Users with non-empty "events" array will produce an NPE when using users.query

### ISSUE THREAD

**Issue by triagonal** [oopsjpeg/osu4j#6]
Problem: Using `osu.users.query` with a username that has a non-empty events array produces an NPE.

Steps to reproduce:
1. Create new Osu API instance with Osu#getAPI
2. Get new OsuUser by using osu.users.query
3. Use username that has non-empty events array (one of the top players usually has something in there, cookiezi for example)
4. Attempt to run program

The issue also occurs when using the Example demo in the README with a non-empty events username.

I'll attach the test I did below, and some other information:
```Java
public class Main {

    public static void main(String[] args) {
        String username = args[0];
        Osu osu = Osu.getAPI(key);
        OsuUser osuUser;

        try {
            System.out.println("Input: " + username);
            osuUser = osu.users.query(new EndpointUsers.ArgumentsBuilder(username).build());
        } catch (OsuAPIException | NullPointerException e) {
            e.printStackTrace();
            return;
        }

        System.out.println(osuUser.getUsername());
    }
}
```

When running with username "cookiezi" (non-empty events)
```
Input: cookiezi
java.lang.NullPointerException
	at com.oopsjpeg.osu4j.OsuUser$Event.<init>(OsuUser.java:224)
	at com.oopsjpeg.osu4j.OsuUser.lambda$new$0(OsuUser.java:60)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.oopsjpeg.osu4j.OsuUser.<init>(OsuUser.java:60)
	at com.oopsjpeg.osu4j.backend.EndpointUsers.query(EndpointUsers.java:27)
	at Main.main(Main.java:15)
```

When running with username "alzase" (empty events)
```
Input: alzase
Alzase
```

Also, here are some photos of the json data for each user at the time that I ran the test:

https://imgur.com/XwQgG1m (cookiezi)
https://imgur.com/lRxWd1E (alzase)

(i'm not 100% certain that the element causing the problem isn't me, but i thought i'd report the issue anyway)

**Comment by triagonal** [comment]
This only seems to occur when using the osu4j jar as a dependency with a manager (tested with maven and gradle) - behavior does not occur when executing the test with source included in the project.

GetUserTest when running with dependency imported with maven:
```Java
Getting user...
Exception in thread "main" java.lang.NullPointerException
	at com.oopsjpeg.osu4j.OsuUser$Event.<init>(OsuUser.java:224)
	at com.oopsjpeg.osu4j.OsuUser.lambda$new$0(OsuUser.java:60)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.oopsjpeg.osu4j.OsuUser.<init>(OsuUser.java:60)
	at com.oopsjpeg.osu4j.backend.EndpointUsers.query(EndpointUsers.java:27)
	at Main.main(Main.java:23)
```

GetUserTest when running with source bundled in project:
```
Getting user...
Cookiezi(124493)
https://osu.ppy.sh/u/124493
Rank: #3
Performance: #3 (14083pp)
Total Score: 187753506865
Top score #1: kradness&Reol - Remote Control [Max Control!] https://osu.ppy.sh/b/774965
Top score #2: xi - FREEDOM DiVE [FOUR DIMENSIONS] https://osu.ppy.sh/b/129891
Top score #3: HoneyWorks - Akatsuki Zukuyo [Taeyang's Extra] https://osu.ppy.sh/b/795627
```

I'm not really sure if i'm just importing the dependency incorrectly, or if there's an issue with the jar (as the issue arises with both maven and gradle). I'll close the issue for now.

UPDATE: recompiling the jar locally with no changes seems to resolve the issue
